package com.maluuba.napi.client;

/**
 * All possible Actions for all possible Categories.
 * 
 * @see <a href="http://developer.maluuba.com/categories">http://developer.maluuba.com/categories/</a> for a detailed description of
 * each Category and Action.
 *
 */
public enum NAPIAction {
  BUSINESS_SEARCH,
  BUSINESS_RESERVATION,
  
  CALL_DIAL,
  CALL_CHECK_MISSED,
  CALL_RESPOND_MISSED,
  CALL_ACCEPT_INCOMING,
  
  CONTACT_SEARCH,
  CONTACT_ADD,
  CONTACT_SET_ALIAS,
  
  KNOWLEDGE_SEARCH,
  
  ENTERTAINMENT_MOVIE,
  ENTERTAINMENT_EVENT,
  ENTERTAINMENT_AMBIGUOUS,
  
  EMAIL_SEND,
  EMAIL_DISPLAY,
  
  HELP_HELP,
  
  TRAVEL_FLIGHT,
  
  MUSIC_PLAY,
  MUSIC_PAUSE,
  
  CALENDAR_CREATE_EVENT,
  CALENDAR_SEARCH,
  CALENDAR_REMOVE_EVENT,
  CALENDAR_MODIFY_EVENT,
  CALENDAR_AVAILABILITY,
  
  WEATHER_STATUS,
  WEATHER_DETAILS,
  WEATHER_SUNSET,
  WEATHER_SUNRISE,
  
  REMINDER_SET,
  REMINDER_SEARCH,
  
  ALARM_SET,
  ALARM_SET_RECURRING,
  ALARM_MODIFY,
  ALARM_CANCEL,
  ALARM_CANCEL_ALL_ALARMS,
  ALARM_SEARCH,
  
  TIMER_START,
  TIMER_DISPLAY,
  TIMER_CANCEL,
  TIMER_PAUSE,
  
  STOPWATCH_START,
  STOPWATCH_STOP,
  STOPWATCH_RESET,
  STOPWATCH_DISPLAY,
  
  NAVIGATION_DIRECTIONS,
  NAVIGATION_WHERE_AM_I,
  
  TRANSIT_NEXT_BUS,
  TRANSIT_NEARBY_STOPS,
  TRANSIT_SCHEDULE,
  TRANSIT_STATIONS,
  
  SEARCH_AMAZON,
  SEARCH_BING,
  SEARCH_EBAY,
  SEARCH_DEFAULT,
  SEARCH_GOOGLE,
  SEARCH_RECIPES,
  SEARCH_VIDEO,
  SEARCH_WIKIPEDIA,
  
  TEXT_DISPLAY,
  TEXT_SEND,
  
  SOCIAL_FACEBOOK_SEND_MESSAGE,
  SOCIAL_FACEBOOK_SHOW_NEWSFEED,
  SOCIAL_FACEBOOK_SHOW_PHOTOS,
  SOCIAL_FACEBOOK_SHOW_WALL,
  SOCIAL_FACEBOOK_WRITE_ON_WALL,
  SOCIAL_FOURSQUARE_CHECK_IN,
  SOCIAL_FOURSQUARE_SHOW_CHECKINS,
  SOCIAL_TWITTER_SHOW_FOLLOWER,
  SOCIAL_TWITTER_SHOW_TRENDING,
  SOCIAL_TWITTER_TWEET,
  
  SPORTS_MISC,
  
  APPLICATION_LAUNCH,

  TVCHANNEL_CHANNEL,
  TVCHANNEL_DOWN,
  TVCHANNEL_UP,
  TVCHANNEL_PREVIOUS,

  TVVOLUME_DOWN,
  /**
   * To re-activate sound, 
   */
  TVVOLUME_MUTE_OFF,
  /**
   * To disable sound
   */
  TVVOLUME_MUTE_ON,
  TVVOLUME_UP
}
